#' @rdname something_akin_to_caching
#' @export
create_and_save_or_load_rds <- function(condition,
                                        expression,
                                        objectName,
                                        path,
                                        prefix = "autogenerated",
                                        suffix = "",
                                        filesToKeep = 2,
                                        silent = metabefor::opts$get("silent")) {
  
  if (!(dir.exists(path))) {
    stop("The directory passed as `path`, '", path,
         "', does not exist.");
  }

  filenameStart <-
    paste0(prefix, "--", objectName, "--", suffix);
    
  fileList <- list.files(
    path,
    pattern=paste0("^", filenameStart, "--.*\\.rds$"),
    full.names=TRUE
  );
    
  if (condition) {

    object <- eval(expression);
    
    ### Delete all but most recent one(s)
    filesToKeepMinusOne <- filesToKeep - 1;
    if (length(fileList) > filesToKeepMinusOne) {
      unlink(head(sort(fileList), -filesToKeepMinusOne));
    }
    
    currentDate <- Sys.time();
    
    fileNameEnd <-
      format(
        currentDate,
        "--%Y-%m-%d--%H-%M.rds"
      );

    fileName <- file.path(path, paste0(filenameStart, fileNameEnd));

    saveRDS(object = object,
            file = fileName);
    
    msg(
      "Saved the produced object to '", fileName, "'.",
      silent = silent
    );

    return(object);
    
  } else {

    if (length(fileList) > 0) {
      filenameToLoad <- tail(sort(fileList), 1);
      res <-
        readRDS(extractedStudiesFilename);
      
      msg(
        "Loaded the requested object from '", filenameToLoad, "'.",
        silent = silent
      );
      
      return(res);
    } else {
      stop("Object `", objectName, "` does not exist, nor is there an ",
           "automatically stored version available to load!");
    }

  }
  
}