#' Something akin to caching
#' 
#' This function check whether an object exists; if it does, it saves
#' it using a system where the number of backups is limited (to 2 files
#' by default), so automatically deleting the oldest version; if it does
#' not exist, it loads one of the automatically saved versions. This
#' functionality can be useful when working with large scripts that
#' take a lot of time to create or process objects.
#'
#' @param object The object to save or load.
#' @param path The directory where to save or load the object (from).
#' @param prefix,suffix A prefix or suffix to add in the filename.
#' @param filesToKeep The number of files to keep.
#'
#' @return The object.
#' @export
save_or_load_rds <- function(object,
                             path,
                             prefix = "autogenerated",
                             suffix = "",
                             filesToKeep = 2) {
  
  if (!(dir.exists(path))) {
    stop("The directory passed as `path`, '", path,
         "', does not exist.");
  }

  # objectNames <-
  #   unlist(lapply(as.list(substitute(...)),
  #                 as.character));
  objectName <- as.character(substitute(object));
  
  # for (currentObject in objectNames) {

    filenameStart <-
      paste0(prefix, "--", objectName, "--", suffix);
    
    ### Get a list of the existing files
    fileList <- list.files(
      path,
      pattern=paste0("^", filenameStart, "--.*\\.rds$"),
      full.names=TRUE
    );
    
    if (exists(object)) {
      
      ### Delete all but most recent one(s)
      filesToKeepMinusOne <- filesToKeep - 1;
      if (length(fileList) > filesToKeepMinusOne) {
        unlink(head(sort(fileList), -filesToKeepMinusOne));
      }
      
      currentDate <- Sys.time();
      
      fileNameEnd <-
        format(
          currentDate,
          "--%Y-%m-%d--%H-%M.rds"
        );

      fileName <- paste0(filenameStart, fileNameEnd);
      
      doCallObject <-
        list(object,
             fileName);
      names(doCallObject) <- c(objectName, "file");
      
      do.call(
        saveRDS,
        doCallObject
      );
      
      return(object);
      
    } else {

      if (length(fileList) > 0) {
        filenameToLoad <- tail(sort(fileList), 1);
        return(readRDS(extractedStudiesFilename));
      } else {
        stop("Object `", objectName, "` does not exist, nor is there an ",
             "automatically stored version available to load!");
      }

    }
  #}
}