#' @rdname something_akin_to_caching
#' @export
save_or_load_csv <- function(object,
                             path,
                             prefix = "autogenerated",
                             suffix = "",
                             filesToKeep = 2,
                             silent = metabefor::opts$get("silent")) {
  
  objectName <- as.character(substitute(object));
  
  if (!is.data.frame(object)) {
    stop("To save to a comma-separated file, you must pass a data frame. ",
         "You passed '", objectName, "' which has class ", vecTxtQ(object),
         ".");
  }
  
  if (!(dir.exists(path))) {
    stop("The directory passed as `path`, '", path,
         "', does not exist.");
  }
  
  filenameStart <-
    paste0(prefix, "--", objectName, "--", suffix);
    
  fileList <- list.files(
    path,
    pattern=paste0("^", filenameStart, "--.*\\.csv$"),
    full.names=TRUE
  );
  
  if (exists(object)) {
    
    ### Delete all but most recent one(s)
    filesToKeepMinusOne <- filesToKeep - 1;
    if (length(fileList) > filesToKeepMinusOne) {
      unlink(head(sort(fileList), -filesToKeepMinusOne));
    }
    
    currentDate <- Sys.time();
    
    fileNameEnd <-
      format(
        currentDate,
        "--%Y-%m-%d--%H-%M.csv"
      );

    fileName <- file.path(path, paste0(filenameStart, fileNameEnd));

    write.csv(
      object,
      fileName
    );
    
    msg(
      "Saved the data frame to '", fileName, "'.",
      silent = silent
    );
    
    return(object);
    
  } else {

    if (length(fileList) > 0) {
      filenameToLoad <- tail(sort(fileList), 1);
      res <- read.csv(filenameToLoad);
      return(res);
    } else {
      stop("Object `", objectName, "` does not exist, nor is there an ",
           "automatically stored version available to load!");
    }

  }
  
}