#' Something akin to caching
#' 
#' These function try to facilitate working with large objects.
#' `save_or_load_rds` checks whether an object exists; if it does, it saves
#' it using a system where the number of backups is limited (to 2 files
#' by default), so automatically deleting the oldest version; if it does
#' not exist, it loads one of the automatically saved versions. This
#' functionality can be useful when working with large scripts that
#' take a lot of time to create or process objects.
#' `create_and_save_or_load_rds` checks the condition; if it's `TRUE`, it
#' executes the expression and saves the result; otherwise, it tries to load
#' the file from disk.
#'
#' @param condition The condition to check.
#' @param object The object to save or load.
#' @param objectName The object to save the expression's result to.
#' @param expression The expression to execute.
#' @param path The directory where to save or load the object (from).
#' @param prefix,suffix A prefix or suffix to add in the filename.
#' @param filesToKeep The number of files to keep.
#' @param silent Whether to be chatty or silent.
#'
#' @return The object.
#' @rdname something_akin_to_caching
#' 
#' @export
save_or_load_rds <- function(object,
                             path,
                             prefix = "autogenerated",
                             suffix = "",
                             filesToKeep = 2,
                             silent = metabefor::opts$get("silent")) {
  
  if (!(dir.exists(path))) {
    stop("The directory passed as `path`, '", path,
         "', does not exist.");
  }
  objectName <- as.character(substitute(object));
  
  filenameStart <-
    paste0(prefix, "--", objectName, "--", suffix);
  
  ### Get a list of the existing files
  fileList <- list.files(
    path,
    pattern=paste0("^", filenameStart, "--.*\\.rds$"),
    full.names=TRUE
  );
  
  if (exists(object)) {
    
    ### Delete all but most recent one(s)
    filesToKeepMinusOne <- filesToKeep - 1;
    if (length(fileList) > filesToKeepMinusOne) {
      unlink(head(sort(fileList), -filesToKeepMinusOne));
    }
    
    currentDate <- Sys.time();
    
    fileNameEnd <-
      format(
        currentDate,
        "--%Y-%m-%d--%H-%M.rds"
      );

    fileName <- file.path(path, paste0(filenameStart, fileNameEnd));
    
    doCallObject <-
      list(object,
           fileName);
    names(doCallObject) <- c(objectName, "file");
    
    do.call(
      saveRDS,
      doCallObject
    );
    
    return(object);
    
  } else {

    if (length(fileList) > 0) {
      filenameToLoad <- tail(sort(fileList), 1);
      res <- readRDS(filenameToLoad);
      return(res);
    } else {
      stop("Object `", objectName, "` does not exist, nor is there an ",
           "automatically stored version available to load!");
    }

  }
  
}